#!/usr/bin/env bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
sketchybar --bar position=top height=40 blur_radius=30 color=0x40000000

# -- Left Side Items --
sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
  sketchybar --add item space.$sid left \
    --subscribe space.$sid aerospace_workspace_change \
    --set space.$sid \
    background.color=0x44ffffff \
    background.corner_radius=5 \
    background.height=20 \
    background.drawing=off \
    label="$sid" \
    click_script="aerospace workspace $sid" \
    script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

default=(
  padding_left=0
  padding_right=0
  icon.font="SF Pro:Semibold:14.0"
  label.font="SF Pro:Semibold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=6
  icon.padding_right=3
  label.padding_left=3
  label.padding_right=3
)
sketchybar --default "${default[@]}"

calendar=(
  calendar icon=􀧞
  label.width=110 \ 
  label.padding_right=0
  update_freq=1 \ 
  script="$PLUGIN_DIR/calendar.sh"
)

battery=(
  update_freq=120
  icon.width=28
  label.padding_left=3 \ 
  script="$PLUGIN_DIR/battery.sh"
)

cpu=(
  icon=􀧓
  script="$PLUGIN_DIR/cpu.sh"
  update_freq=15
)

media=(
  icon=􀊕
  icon.padding_left=0
  script="$PLUGIN_DIR/media.sh"
)

volume=(
  icon.width=27
  label.padding_right=0
  label.padding_left=0
  script="$PLUGIN_DIR/volume.sh"
)

ram=(
  ram icon=􀧖
  label.padding_right=0
  update_freq=15
  script="$PLUGIN_DIR/ram.sh"
)

# -- Right Side Notch Items --
sketchybar --add item media e --set media "${media[@]}" --subscribe media media_change

# -- Right Side Items --
sketchybar --add item calendar right --set calendar "${calendar[@]}"
# sketchybar --add item volume right --set volume "${volume[@]}" --subscribe volume volume_change
sketchybar --add item battery right --set battery "${battery[@]}" --subscribe battery system_woke power_source_change
sketchybar --add item cpu right --set cpu "${cpu[@]}"
sketchybar --add item ram right --set ram "${ram[@]}"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
