#!/usr/bin/env bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
sketchybar --bar position=top height=40 blur_radius=30 color=0x40000000

default=(
  padding_left=0
  padding_right=0
  icon.font="SF Pro:Semibold:14.0"
  label.font="SF Pro:Semibold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=6
  icon.padding_right=3
  label.padding_left=3
  label.padding_right=3
)
sketchybar --default "${default[@]}"

# -- AeroSpace layout --
# Add the aerospace_workspace_change event we specified in aerospace.toml
sketchybar --add event aerospace_workspace_change

# This only works for single monitor configs!
for sid in $(aerospace list-workspaces --monitor 1); do
  #for sid in "${SPACE_IDS[@]}"; do
  sketchybar --add item space.$sid left \
    --subscribe space.$sid aerospace_workspace_change \
    --set space.$sid \
    drawing=off \
    background.color=0x44ffffff \
    background.corner_radius=5 \
    background.drawing=on \
    background.border_color=0xAAFFFFFF \
    background.border_width=0 \
    background.height=25 \
    icon="$sid" \
    icon.padding_left=10 \
    icon.shadow.distance=4 \
    icon.shadow.color=0xA0000000 \
    label.font="sketchybar-app-font:Regular:16.0" \
    label.padding_right=20 \
    label.padding_left=0 \
    label.y_offset=-1 \
    label.shadow.drawing=off \
    label.shadow.color=0xA0000000 \
    label.shadow.distance=4 \
    click_script="aerospace workspace $sid" \
    script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

# Load Icons on startup
for sid in $(aerospace list-workspaces --monitor 1 --empty no); do
  apps=$(aerospace list-windows --workspace "$sid" | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')

  sketchybar --set space.$sid drawing=on

  icon_strip=" "
  if [ "${apps}" != "" ]; then
    while read -r app; do
      icon_strip+=" $($CONFIG_DIR/plugins/icon_map_fn.sh "$app")"
    done <<<"${apps}"
  else
    icon_strip=""
  fi
  sketchybar --set space.$sid label="$icon_strip"
done

sketchybar --add item space_separator left \
  --set space_separator icon="💩" \
  icon.padding_left=4 \
  label.drawing=off \
  background.drawing=off \
  script="$PLUGIN_DIR/space_windows.sh" \
  --subscribe space_separator aerospace_workspace_change

# Front app!!
sketchybar --add item front_app left \
  --set front_app icon.drawing=off \
  script="$PLUGIN_DIR/front_app.sh" \
  --subscribe front_app front_app_switched

calendar=(
  calendar icon=􀧞
  label.width=110 \ 
  label.padding_right=0
  update_freq=1 \ 
  script="$PLUGIN_DIR/calendar.sh"
)

battery=(
  update_freq=120
  icon.width=28
  label.padding_left=3 \ 
  script="$PLUGIN_DIR/battery.sh"
)

cpu=(
  icon=􀧓
  script="$PLUGIN_DIR/cpu.sh"
  update_freq=15
)

media=(
  icon=􀊕
  icon.padding_left=0
  script="$PLUGIN_DIR/media.sh"
)

volume=(
  icon.width=27
  label.padding_right=0
  label.padding_left=0
  script="$PLUGIN_DIR/volume.sh"
)

ram=(
  ram icon=􀧖
  label.padding_right=0
  update_freq=15
  script="$PLUGIN_DIR/ram.sh"
)

# -- Right Side Notch Items --
sketchybar --add item media e --set media "${media[@]}" --subscribe media media_change

# -- Right Side Items --
sketchybar --add item calendar right --set calendar "${calendar[@]}"
# sketchybar --add item volume right --set volume "${volume[@]}" --subscribe volume volume_change
sketchybar --add item battery right --set battery "${battery[@]}" --subscribe battery system_woke power_source_change
sketchybar --add item cpu right --set cpu "${cpu[@]}"
sketchybar --add item ram right --set ram "${ram[@]}"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
