#!/usr/bin/env bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
sketchybar --bar position=top height=40 blur_radius=30 color=0x40000000

default=(
  padding_left=0
  padding_right=0
  icon.font="SF Pro:Semibold:14.0"
  label.font="SF Pro:Semibold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=6
  icon.padding_right=3
  label.padding_left=3
  label.padding_right=3
)
default_simple=(
  padding_left=0
  padding_right=0
  icon.font="SF Pro:Semibold:13.8"
  label.font="SF Pro:Semibold:13.8"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=6
  icon.padding_right=3
  label.padding_left=3
  label.padding_right=3
)
sketchybar --default "${default_simple[@]}"

# -- AeroSpace layout --
# Add the aerospace_workspace_change event we specified in aerospace.toml
# sketchybar --add event aerospace_workspace_change

# This only works for single monitor configs!
for sid in $(aerospace list-workspaces --monitor 1); do
  #for sid in "${SPACE_IDS[@]}"; do
  sketchybar --add item space.$sid left \
    --subscribe space.$sid aerospace_workspace_change \
    --set space.$sid \
    drawing=off \
    background.color=0x44ffffff \
    background.corner_radius=5 \
    background.drawing=on \
    background.border_color=0xAAFFFFFF \
    background.border_width=0 \
    background.height=25 \
    icon="$sid" \
    icon.padding_left=10 \
    icon.shadow.distance=4 \
    icon.shadow.color=0xA0000000 \
    label.font="sketchybar-app-font:Regular:16.0" \
    label.padding_right=20 \
    label.padding_left=0 \
    label.y_offset=-1 \
    label.shadow.drawing=off \
    label.shadow.color=0xA0000000 \
    label.shadow.distance=4 \
    click_script="aerospace workspace $sid" \
    script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

calendar=(
  calendar icon=􀧞
  label.width=110 \ 
  label.padding_right=0
  update_freq=1 \ 
  script="$PLUGIN_DIR/calendar.sh"
)

time=(
  label.width=110 \ 
  label.padding_right=0
  script="$PLUGIN_DIR/time.sh"
  update_freq=1 \ 
)

date=(

  label.padding_right=0
  script="$PLUGIN_DIR/date.sh"
  update_freq=60\ 
)

battery=(
  update_freq=120
  icon.width=28
  label.padding_left=3 \ 
  script="$PLUGIN_DIR/battery.sh"
)

cpu=(
  icon=􀧓
  script="$PLUGIN_DIR/cpu.sh"
  update_freq=15
)

media=(
  icon=􀊕
  icon.padding_left=0
  script="$PLUGIN_DIR/media.sh"
)

volume=(
  icon.width=27
  label.padding_right=0
  label.padding_left=0
  script="$PLUGIN_DIR/volume.sh"
)

ram=(
  ram icon=􀧖
  label.padding_right=0
  update_freq=15
  script="$PLUGIN_DIR/ram.sh"
)

# -- Left Side Notch Items --
sketchybar --add item battery q --set battery "${battery[@]}" --subscribe battery system_woke power_source_change

# -- Right Side Notch Items --
sketchybar --add item time e --set time "${time[@]}"
# sketchybar --add item media e --set media "${media[@]}" --subscribe media media_change

# -- Right Side Items --
sketchybar --add item date right --set date "${date[@]}"
# sketchybar --add item calendar right --set calendar "${calendar[@]}"
# sketchybar --add item volume right --set volume "${volume[@]}" --subscribe volume volume_change
# sketchybar --add item battery right --set battery "${battery[@]}" --subscribe battery system_woke power_source_change
# sketchybar --add item cpu right --set cpu "${cpu[@]}"
# sketchybar --add item ram right --set ram "${ram[@]}"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
